PATH:
    OUTPUT_DIR:        "./Output"
    video_path:        "./Videos/test.mp4"
    labels_file:       "./coco.names"

FRAME:
    read_from_video:   True
    frame_dir_path:    "./Output/Videos/test"

OPTION:
    write_txt:         True
    remove_json:       True
    show_video:        True
    delete_one_class:  False

ACTION:
    get_frame_range:   False
    frame_range:       [2, 100]
    start_mode:        "r"

